var a=" lesgo";
document.write(a); 
document.write(a); 
document.write(a); 
a=" orange";
document.write(a); 
document.write(a); 
a=" apple";
document.write(a); document.write(a); 
alert("how you doin'?");
document.write("<br>");
var age= 18;
var gpa= 3.1;
var ismale= true;
document.write(age);
document.write(gpa);
document.write(ismale); 
document.write("<br>"); 
var description= undefined;
document.write(description); 
